services:
  mongo:
    image: mongo:6

  backend-e2e:
    build:
      context: ./server
      target: prod
    environment:
      NODE_ENV: test
      MONGO_URI: mongodb://mongo:27017/testdb
      JWT_SECRET: test_jwt_secret
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  backend-test:
    build:
      context: ./server
      target: test
    environment:
      NODE_ENV: test
      MONGO_URI: mongodb://mongo:27017/testdb
      JWT_SECRET: test_jwt_secret
    depends_on:
      - mongo

  frontend-test:
    build:
      context: ./client/my-project
      target: test
    environment:
      VITE_API_BASE_URL: http://backend-e2e:5000
      PLAYWRIGHT_BASE_URL: http://localhost:4173
    depends_on:
      - backend-e2e
    ports:
      - "4173:4173"
