apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-notes-backend
  namespace: ai-notes
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: avvatni/ai-notes-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ai-notes-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ai-notes-config
              key: NODE_ENV
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: ai-notes-config
              key: CLIENT_URL
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: ai-notes-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-notes-secrets
              key: JWT_SECRET
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-notes-secrets
              key: GEMINI_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

