apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ai-notes
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30008
    protocol: TCP
    name: http
  selector:
    app: prometheus
